line-length = 128
target-version = "py314"

[lint]
select = ["ALL"]

[lint.isort]
required-imports = ["from __future__ import annotations"]

[lint.per-file-ignores]

[format]
# Don't apply line-length formatting to comments
skip-magic-trailing-comma = true
quote-style = "double"
docstring-code-format = true
